import type { Metadata } from "next";
import "./globals.css";
import { Urbanist, Space_Grotesk } from 'next/font/google';
import NavBar from "@/components/NavBar";

const urbanist = Urbanist({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-urbanist',
});

const spaceGrotesk = Space_Grotesk({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-space-grotesk',
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${urbanist.className} ${spaceGrotesk.className} antialiased`}
      >
        <NavBar/>
        {children}
      </body>
    </html>
  );
}
